### ISSUE TITLE
Can not find Symbolic Arrays support

### ISSUE THREAD

**Issue by Kurt212** [psycopaths/jconstraints#2]
In this [article](https://users.ece.cmu.edu/~afromher/papers/jpf2016-array.pdf), authors said, that they extended Jconstraints and Jconstraints-Z3 to support Symbolic Arrays, select and store operations. (They added base classes for ArrayExpression, SelectExpression and StoreExpression).

Can you help me to find these changes?

**Comment by fhowar** [comment]
Please contact the authors of the paper. As far as I know, the extension was not made available publicly.

**Comment by Kurt212** [comment]
Thank you for your answer!

I found this Jconstraints version https://github.com/R1kM/jconstraints, where symbolic arrays are implemented.
